### ISSUE TITLE
DataBuri -  all-in-one Python package for Thailand's public APIs

### ISSUE THREAD

**Issue by p16i** [codeforthailand/welcome#2]
Project Proposal for [Data Innovation Awards Thailand 2019][dia] : [Link][link]

I haven't done anything for this project yet. It's just an idea. Maybe we can add it later when we have something there. 

In short, this project aims to develop a all-in-one Python package. It should provide a unified interface for users to retrieve data from Thailand's public data APIs or datasets with only few configuration.

The package has 2 major parts: Datasource & Dataset

Datasource is related to public APIs. Most likely, every module in this part is developed for each data API. Mostly likely, these modules are just REST clients with options to specify authentication keys.

Dataset is mainly for static datasets, mainly for training ML algorithms.

List of Public Data APIs

- https://govspending.data.go.th/api/documentation
- https://api-portal.sec.or.th
- http://opend.openservice.in.th/opend/
- http://dolwms.dol.go.th/tvwebp/?fbclid=IwAR2YeVAgnMzPOrIo9CpQXK-r74-Gm6SFcghjXpNTJ9sDv9B2LLmn5u7OyQY
- https://data.moc.go.th/?fbclid=IwAR3aAEird62hsNHemDXRnkXRJIgw5MwgRARjnDjtvraWZH92jmnipinlFZc
List of datasets

- wongnai
- https://github.com/nextwaverr/Thai-MNIST
- https://developer.scb/#/home

Repository: https://github.com/codeforthailand/databuri

[link]: https://docs.google.com/document/d/1XXuRovZ3bRGC18MQluO5zsZJ_6TM9COwCgRoWv6lsnM/edit?usp=sharing&fbclid=IwAR19HYR49MvKnd_Ot6kxguMjoS_rMdxFaSF2c-pxpbZtCP-wFGIRyDUgbZk 

[dia]: https://www.diathailand.com

**Comment by unnawut** [comment]
Closed by 2b486f0
